### ISSUE TITLE
error while loading shared libraries: libboost_program_options.so.1.42.0

### ISSUE THREAD

**Issue by xreader** [beschulz/wav2png#20]
after installation (i tried both apt.get and homebrew) by executing command 

```bash

./libs/wav2png-master/bin/Linux/wav2png --foreground-color=2e4562ff --background-color=00000000 -o public/uploads/3gwl5n6wv9557v0r1f.wav ../short.wav

```
i get this error

./libs/wav2png-master/bin/Linux/wav2png: error while loading shared libraries: libboost_program_options.so.1.42.0: cannot open shared object file: No such file or directory

i run ubuntu 

LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by fergalmoran** [comment]
You're missing the boost library, make sure to install all the dependencies listed in the README

    apt-get install make g++ libsndfile1-dev libpng++-dev libpng12-dev libboost-program-options-dev

**Comment by xreader** [comment]
i installed them all but i still get this the error

sudo apt-get install make g++ libsndfile1-dev libpng++-dev libpng12-dev
libboost-program-options-dev
[sudo] password for xreader:
Reading package lists... Done
Building dependency tree
Reading state information... Done
g++ is already the newest version.
libboost-program-options-dev is already the newest version.
libpng12-dev is already the newest version.
libsndfile1-dev is already the newest version.
make is already the newest version.
libpng++-dev is already the newest version.
The following packages were automatically installed and are no longer
required:
  wine-compholio wine-compholio-amd64 wine-compholio-i386:i386
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.

**Comment by xreader** [comment]
I realized that i have later version of libboost_program_options (1.54.0)

i tried to install 1.42 version with no success

```
(Reading database ... 870129 files and directories currently installed.)
Preparing to unpack .../libboost1.42-dev_1.42.0-4ubuntu3_i386.deb ...
Unpacking libboost1.42-dev (1.42.0-4ubuntu3) ...
dpkg: dependency problems prevent configuration of libboost1.42-dev:
 libboost1.42-dev depends on libstdc++6-4.4-dev | libstdc++-dev.

dpkg: error processing package libboost1.42-dev (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 libboost1.42-dev
```

is it possible to update wav2png to use newer libraries?

**Comment by beschulz** [comment]
Are you compiling wav2png yourself or are you trying to use the pre-build binary?

**Comment by xreader** [comment]
I tried to compile myself the way described in README

build is always failed because the required (older) version of
libboost-program-options-dev
is no more available for ubuntu.

but it's ok i found another library to generate image from audio file

**Comment by mardix** [comment]
I ran into something similar. 

What I did, I remove the `wav2png/bin` directory, and then I did `make all`, everything worked fine.

Good luck!
