### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by CamilloBovio** [beschulz/wav2png#21]
I've followed installation guide lines and all is ok, but when i type "wav2png" or "wav2png --help" into terminal returns me " Illegal instruction: 4 ". I'm running OS X 10.7.5.

How can i fix it?

Thanks

**Comment by beschulz** [comment]
Hi,

I recently ran into this issue as well. Please make sure, that don't use the binary from the repository (bin/Darwin/wav2png). It would be best, if you delete it and do a recompile. (I should probably delete the binary from the repository)

**Comment by CamilloBovio** [comment]
Thanks for your very quick reply! i've fixed with:
sudo cp bin/Darwin/wav2png /usr/local/bin/

Very thanks for your support!

**Comment by beschulz** [comment]
You're welcome!
