### ISSUE TITLE
batch_process.py yeilds no output

### ISSUE THREAD

**Issue by akasoldats** [beschulz/wav2png#22]
When I run batch process.py on a set of files that worked with wav2png the program silently fails. I have tried changing directorys, using different files and even multiple image options however it doesn't seem to begin processing. However no errors are reported. Am I dont something wrong here?

**Comment by beschulz** [comment]
Just a hunch, but are you on windows and do your paths contain backslashes?

If that's the case, you need to either escape your backslashes:
INPUT_DIRECTORY  = 'd:\\samples\\awesome'
OUTPUT_DIRECTORY = 'c:\\blah\\bluh'

or use pythons raw strings:
INPUT_DIRECTORY  = r'd:\samples\awesome'
OUTPUT_DIRECTORY = r'c:\blah\bluh'

but yeah - no error message is not a good thing, I agree …

**Comment by akasoldats** [comment]
Unfortunately not, I am using this on "12.04.5 LTS, Precise Pangolin". My file paths are as follows:

INPUT_DIRECTORY  = '/optimus/data/Updates/Hard\ Drives/WAVE\ DRIVE\ 092015/'
OUTPUT_DIRECTORY = '/optimus/data/misc'

**Comment by beschulz** [comment]
I see. just get rid of the backslashes.

**Comment by beschulz** [comment]
INPUT_DIRECTORY = '/optimus/data/Updates/Hard Drives/WAVE DRIVE 092015/'

should work

**Comment by akasoldats** [comment]
Awesome, that worked! Haha, I failed to realize the paths didnt need to be escaped. Thanks!
