### ISSUE TITLE
segmentation fault  ./wav2png ?

### ISSUE THREAD

**Issue by hems** [beschulz/wav2png#25]
wav2png used to work perfectly but suddenly when i try to use it i get the following error:

````
[1]    13806 segmentation fault  ./wav2png
````

the funny thing is that this error happened on my desktop computer and then when i moved onto my laptop i found out the same error is happening too, but theoretically nothing has changed in both machines since the last time i used it successfully.

any ideas?

**Comment by beschulz** [comment]
Can you do a re-compile, e.g. make clean && make all and see if the problem
persists?

**Comment by hems** [comment]
@beschulz i had this issue when trying to recompile: https://github.com/beschulz/wav2png/issues/24

luckily i found the wav2png binary on the repository history under darwin/bin .... why did you guys delete it? it was very useful for me! i would have been in big trouble if i didn't find it on the history.

**Comment by beschulz** [comment]
I have deleted it, because it can cause trouble if you have different
library versions installed then the ones the binary was compiled against or
can cause some head scratching if the required libraries are not installed
at all.

Glad you could get it to work.
Ben

henrique matias <notifications@github.com> schrieb am Di., 23. Feb. 2016,
17:24:

**Comment by hems** [comment]
@beschulz still i can't compile the "master" version of the repo. so please have a look on the other issue!

**Comment by beschulz** [comment]
Hi hems,

can you give more details on why you can't compile? I'm closing this now, but please feel free to re-open if you still cannot compile.

**Comment by hems** [comment]
i'll try it again as soon as i have a chance, sorry i been away from this for some time now
