### ISSUE TITLE
Support for BWF (Broadcast WAVE)?

### ISSUE THREAD

**Issue by eborned** [beschulz/wav2png#26]
I'm currently using this tool to process a lot of WAV files from different sources. One of the problems it that our sources sometimes use BWF files. This means the WAV has additional meta-data in the header. I believe this tool is using libsndfile, but that library has support for BWF chunks in the header. 

The problem is: when I try to use the tool on a BWF file, I get:

Not a valid error number (-1).
Segmentation fault

If I try on normal WAV files, without the extra metadata, it works great.

**Comment by beschulz** [comment]
Hey Eric,

can you provide me a short/small example file to reproduce the Problem?

Best,
Ben

Eric Bus <notifications@github.com> schrieb am Do., 14. Apr. 2016, 15:47:

**Comment by eborned** [comment]
My bad, I just noticed that wav2png was using the wrong libsndfile. I had a new version available in /usr/local/lib, and my old (CentOS5) version in /usr/lib. The old version does not support BWF, the newly compiled version does. The actual message (Not a valid number) came from libsndfile, so I guess it was a bug in the older library that is fixed.
