### ISSUE TITLE
Any possibility of a non-X11 version of the droplet?

### ISSUE THREAD

**Issue by weavermedia** [beschulz/wav2png#28]

**Comment by HybridDog** [comment]
There's another waveform analysing program, but it's 3d (x: time, y: frequency, z: amount):
http://spek.cc/
(wav2png obviously: x: time, y: amount)

**Comment by beschulz** [comment]
@weavermedia : I don't really get it. The droplet is pure osx UI.

**Comment by HybridDog** [comment]
Maybe they means running it without a gui, e.g. using the console.

**Comment by beschulz** [comment]
@HybridDog but this is mainly a command line utility. The dropplet is merely a gimmick. :/

**Comment by HybridDog** [comment]
X11 doesn't mean OSX 11, does it?

**Comment by beschulz** [comment]
No X11 is a windowing system and OS X (or macOS) is Apples operating system. so they are two different things. There is however the possibility to use X11 on macOS as well (like Wireshark did). But the droplet does not do that. So I remain puzzled.

**Comment by HybridDog** [comment]
Maybe weavermedia wants to have a Windows version of the droplet

**Comment by beschulz** [comment]
maybe ...
