### ISSUE TITLE
wav2png: error while loading shared libraries: libboost_program_options.so.1.62.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dreaddymck** [beschulz/wav2png#32]
### install dependencies
```apt-get install make g++ libsndfile1-dev libpng++-dev libpng12-dev libboost-program-options-dev``

libpng12-dev is no longer available. Installed libpng-dev

```
make all
echo "#ifndef VERSION_HPP__" > ../src/version.hpp
echo "#define VERSION_HPP__" >> ../src/version.hpp
echo "namespace {" >> ../src/version.hpp
echo "  namespace version {" >> ../src/version.hpp
echo "          static const std::string date=\"`date`\";" >> ../src/version.hpp
echo "          static const std::string platform=\"Linux\";" >> ../src/version.hpp
echo "          static const std::string version=\"`cat version.txt`\";" >> ../src/version.hpp
echo "  }; /* namespace version */" >> ../src/version.hpp
echo "} /* anonymous namespace */" >> ../src/version.hpp
echo "#endif /* VERSION_HPP__ */" >> ../src/version.hpp
mkdir -p `dirname ../bin/Linux/wav2png`
echo -I../dependencies/include
-I../dependencies/include
# -Wno-unused-local-typedefs
g++ -O3 -Wall -Werror ../src/*.cpp -I../dependencies/include -lboost_program_options `libpng-config --ldflags` -lsndfile -o ../bin/Linux/wav2png
```
How to fix?

**Comment by beschulz** [comment]
Either your installation of libboost_program_options is borked or it's installed to some location not in the library search path. in the former case, re-install the library, clean and re-build. In the latter case: find the directory where the lib is located and run the program with

LD_LIBRARY_PATH=/path/to/lib wav2png

These problems are however not specific to wav2png.

**Comment by dreaddymck** [comment]
Agreed.
It is a result of OS upgrade and library changes. Irritating to say the least. 
Closing as this thread as this is not a wav2png specific issue.
