### ISSUE TITLE
Are generated images not subject to the GPL-2?

### ISSUE THREAD

**Issue by developer-acc** [beschulz/wav2png#38]
Hello, I was wondering if I could use images generated by `wav2png` in my other `non-GPL` project, would it comply with the `GPL-2` license?
My binary & source code won't include wav2png code (both dynamically and statically), just images.

**Comment by beschulz** [comment]
Hi,

thanks for asking. From my perspective you can do with the output
whatever you want. IMHO I can't impose some license on the output of a
merely transformative process. Imagine gimp would put saved images under
the GPL whenever you slightly adjust the contrast of an image and save it.

But I am not a lawyer by any stretch of the imagination.

All the best,
Ben
